export const serviceTypes = [
  {
    code: "accounts_tracking",
    name: "Accounts Tracking",
    description: "Annual accounts tracking",
    availableForIndividuals: false,
    availableForCompanies: true,
    availableForPartnerships: true,
  },
  {
    code: "self_assessment",
    name: "Self Assessment",
    description: "Self Assessment tax returns",
    availableForIndividuals: true,
    availableForCompanies: true,
    availableForPartnerships: true,
  },
  {
    code: "vat",
    name: "VAT",
    description: "VAT Returns",
    availableForIndividuals: true,
    availableForCompanies: true,
    availableForPartnerships: true,
  },
  {
    code: "cis",
    name: "CIS",
    description: "Construction Industry Scheme",
    availableForIndividuals: true,
    availableForCompanies: true,
    availableForPartnerships: true,
  },
  {
    code: "paye",
    name: "PAYE",
    description: "Payroll",
    availableForIndividuals: true,
    availableForCompanies: true,
    availableForPartnerships: true,
  },
  {
    code: "confirmation_statement",
    name: "Confirmation Statement",
    description: "Companies House confirmation statement",
    availableForIndividuals: false,
    availableForCompanies: true,
    availableForPartnerships: false,
  },
  {
    code: "aml",
    name: "AML",
    description: "Anti Money Laundering",
    availableForIndividuals: true,
    availableForCompanies: false,
    availableForPartnerships: false,
  },
  {
    code: "mtd_itsa",
    name: "MTD ITSA",
    description: "Making Tax Digital for Income Tax",
    availableForIndividuals: true,
    availableForCompanies: false,
    availableForPartnerships: false,
  },
];